### ISSUE TITLE
Add `dist2coast` function or mask

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esmtools#10]
There's been many cases where I needed to filter something as being N kilometers from some coastline. My old advisor had a MATLAB script for this. Most recently, I coarsened a file I found on the Navy's website.

I'll dig up that and try to make a mask out of it that can then be remapped to any grid.

**Comment by aaronspring** [comment]
Isn’t this something for esmask?

**Comment by bradyrx** [comment]
Yeah that's probably true. I'll move it over there.
