### ISSUE TITLE
stats.linear_slope slow

### ISSUE THREAD

**Issue by aaronspring** [bradyrx/esmtools#101]
`stats.linear_slope` is quite slow compared to
```python
def slope(da, dim='time'):
    deg=1
    return da.polyfit(dim=dim, deg=deg).sel(degree=deg,drop=True)
```
I know you put lots of effort into the function and xarray had the development shortly later.
I think we should get rid of our implementation.

**Comment by bradyrx** [comment]
Yeah it just so happened that it came out around the time I worked on all this. I think we can switch over to that or just remove it if there's a direct way through `xarray`. I'm in favor of keeping things like `linregress` that offer additional functionality -- i.e., the ability to get slope, intercept, p, corr, etc.

**Comment by aaronspring** [comment]
See https://github.com/pangeo-data/climpred/blob/68629d831d6f61848eb5d10f10399edbd72876f1/climpred/stats.py#L14 for faster
