### ISSUE TITLE
GitHub workflows "Set up conda" step failing

### ISSUE THREAD

**Issue by luke-gregor** [bradyrx/esmtools#104]
PR #99 failing due to CI set up. 

I think this might be due to an outdated GitHub actions recipe. 

https://github.com/bradyrx/esmtools/blob/27e58176ce8f00d1fd94279bdcfba242fd9c8de3/.github/workflows/esmtools_testing.yml#L21-L28

I'm using the following config for my cookiecutter repo. Last time I tried, it was passing. But the steps look almost identical to what you're running 🤔
https://github.com/luke-gregor/cookiecutter-conda-gh_actions/blob/0159bb4ee05ee4cbc906228497394ad554417880/%7B%7Bcookiecutter.repo_name%7D%7D/.github/workflows/test.yml#L21-L29

**Comment by bradyrx** [comment]
Ah man. I'll give this a look. It was running fine when I set it up. Thanks for the heads up.

**Comment by bradyrx** [comment]
I basically just lifted what we're doing over at `climpred` and put it here. https://github.com/pangeo-data/climpred/blob/master/.github/workflows/climpred_testing.yml

**Comment by bradyrx** [comment]
Perhaps one of those upstream things that just pops up: https://github.com/djjudas21/camerahub/issues/630.

**Comment by bradyrx** [comment]
Opened an issue here at their hook: https://github.com/conda-incubator/setup-miniconda/issues/101.

**Comment by bradyrx** [comment]
Okay they were already aware, just need to bump to version v2. https://github.com/openforcefield/openforcefield/blob/master/.github/workflows/CI.yml#L60

**Comment by bradyrx** [comment]
Addressed in https://github.com/bradyrx/esmtools/pull/105.
