### ISSUE TITLE
hatching

### ISSUE THREAD

**Issue by aaronspring** [bradyrx/esmtools#13]
How do you do hatching? In NCL it was easy, somehow in python I dont really get it.

I use cartopy and pcolormesh. The only way that works with me is:

```python
control.plot()
plt.contourf(mask.lon, mask.lat, mask, hatches='x')
```

If its not straight forward we could include it in graphics. I didnt find hatching in proplot with cartopy.

**Comment by bradyrx** [comment]
Honestly, I haven't done any hatching on maps with matplotlib or cartopy. The hatching under "inverse scales" is nice here: https://lukelbd.github.io/tools/proplot but I don't see anything for maps.

---

My searches tend to agree with you that `contourf` is the only way to do it. It isn't implemented in `pcolormesh` and they don't plan to do so (https://github.com/matplotlib/matplotlib/issues/3058). It is implemented in `pcolor` (with the keyword "hatch") but that's much too slow.

<img width="776" alt="screen shot 2019-02-01 at 11 10 21 am" src="https://user-images.githubusercontent.com/8881170/52141112-fc421700-2611-11e9-9feb-6dc7e43686ff.png">
