### ISSUE TITLE
weights, clims

### ISSUE THREAD

**Issue by aaronspring** [bradyrx/esmtools#14]
Do you use esmlab so far?

This seems really nice to me for weighted averages and stuff...
https://github.com/NCAR/esmlab/

**Comment by aaronspring** [comment]
I just saw that there will be more python in the future... http://www.ncl.ucar.edu/open_letter_to_ncl_users.shtml

**Comment by bradyrx** [comment]
I heard recently about NCL switching over to python, but I think it will take awhile for development.

I've never used esmlab. It looks useful, but I wouldn't say it adds much more on top of our `area_weight` functions. It's good to be aware of in the future though in case we need to do other weighting operations and want to just bring that package in.
