### ISSUE TITLE
`xr_area_weight` should maintain attributes, etc.

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esmtools#18]
Currently, `xr_area_weight` returns an unnamed DataArray. I always find myself renaming the DataArray after so I can convert it back to a Dataset. I need to go back through this with a careful eye.

**Comment by aaronspring** [comment]
they will soon add something like this to xarray: https://github.com/pydata/xarray/pull/2922

**Comment by bradyrx** [comment]
That looks nice.

**Comment by bradyrx** [comment]
Looks like you can pass `keep_attrs=True` to functions, e.g. `.mean(keep_attrs=True)` https://github.com/pydata/xarray/issues/442

**Comment by aaronspring** [comment]
and this can be set globally for xr

**Comment by bradyrx** [comment]
Yeah but I think the argument is that there are certain functions where you don't want attributes maintained. But I'm not sure what those would be. So maybe we set this in the `__init__` function or something.

**Comment by bradyrx** [comment]
`area_weight` should be deprecated anyways in favor of `xarray`'s weighted objects.
