### ISSUE TITLE
Travis breaking

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esmtools#24]
Need to fix travis build since it's breaking. Don't have the patience or time to do it right now.

**Comment by aaronspring** [comment]
Haven’t seen that. Maybe travis requires running some testing like pytest

**Comment by aaronspring** [comment]
https://docs.travis-ci.com/user/languages/python/

**Comment by bradyrx** [comment]
Yep I'll try again when I implement some testing. This isn't a huge deal, since `esmtools` is low priority and a hodge-podge of functions. I'm just seeing the benefit of automation at `climpred` and it'll be helpful here too to avoid headaches.

**Comment by bradyrx** [comment]
Resolved by adding one dummy test for now.
