### ISSUE TITLE
modifications to linregress

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esmtools#25]
These came up when helping out Genvieve:

1. This should leave the p-values unmasked so you can see what the other p-values were.

https://github.com/bradyrx/esmtools/blob/7365b4f35d00d3fd77cc2d716d1fff08df5ea1d3/esmtools/stats.py#L163-L164

2. If you input a dask array it doesn't work since `dask=parallelized` can't support dataset returns.

3. If there's any NaNs in the timeseries, it NaNs that whole thing. Need to do simple interpolation for NaNs so folks can work with observational datasets. I think @ahuang11 handled this in `climpred`.

**Comment by bradyrx** [comment]
From `climpred`:

```python
da_dims_orig = list(da.dims)  # orig -> original
    if len(da_dims_orig) > 1:
        # want independent axis to be the leading dimension
        da_dims_swap = da_dims_orig.copy()  # copy to prevent contamination

        # https://stackoverflow.com/questions/1014523/
        # simple-syntax-for-bringing-a-list-element-to-the-front-in-python
        da_dims_swap.insert(0, da_dims_swap.pop(da_dims_swap.index(dim)))
        da = da.transpose(*da_dims_swap)

        # hide other dims into a single dim
        da = da.stack({'other_dims': da_dims_swap[1:]})
        dims_swapped = True
    else:
        dims_swapped = False

    # NaNs will make the polyfit fail--interpolate any NaNs in
    # the provided dim to prevent poor fit, while other dims' NaNs
    # will be filled with 0s; however, all NaNs will be replaced
    # in the final output
    nan_locs = np.isnan(da.values)

    # any(nan_locs.sum(axis=0)) fails if not 2D
    if nan_locs.ndim == 1:
        nan_locs = nan_locs.reshape(len(nan_locs), 1)
        nan_reshaped = True
    else:
        nan_reshaped = False

    # check if there's any NaNs in the provided dim because
    # interpolate_na is computationally expensive to run regardless of NaNs
    if any(nan_locs.sum(axis=0)) > 0:
        if any(nan_locs[0, :]):
            # [np.nan, 1, 2], no first value to interpolate from; back fill
            da = da.bfill(dim)
        elif any(nan_locs[-1, :]):
            # [0, 1, np.nan], no last value to interpolate from; forward fill
            da = da.ffill(dim)
        else:  # [0, np.nan, 2], can interpolate
            da = da.interpolate_na(dim)
```

**Comment by ahuang11** [comment]
> 2. If there's any NaNs in the timeseries, it NaNs that whole thing. Need to do simple interpolation for NaNs so folks can work with observational datasets. I think @ahuang11 handled this in `climpred`.

Actually I think it temporarily interpolates the NaNs in the primary dim (time), but replaces the NaNs in the end. The other dims' (lon, lat, i.e. land) NaNs are filled with 0s since they don't affect the fit, but I think also filled back with NaNs in the end.

e.g.
`ts = [0, 1, np.nan, 2]`
in the process:
`ts = [0, 1, 1.5, 2]`
finally:
`ts = [0, 1, np.nan, 2, 3]`
