### ISSUE TITLE
Detect limiting nutrient in each grid cell

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esmtools#6]
Per @aaronspring in https://github.com/bradyrx/climpred/issues/23#issuecomment-453634686. We should have functions related to detecting whether there is a limiting nutrient in the given grid cell and if so, what it is.

**Comment by aaronspring** [comment]
this might also be model dependent.

what the script does: (originally a bash script from a collegue, have to check back with her)
convert all nutrients into phosphate units
check which is lowest, creates masks and give a factor for nutrient limitation (1 being pp is limited by nutrients)

https://github.com/bradyrx/esmtools/blob/8debf88c1b557a59bb372ef45a0abccab141284d/notebooks/Primary_Production.ipynb

**Comment by bradyrx** [comment]
@aaronspring, this is a nice demo, thanks. I think it's okay to just submit some of these things as notebooks for us to reference. This one will go in with your PR once you respond to my review (I had this done awhile ago and forgot to press "submit review")

**Comment by aaronspring** [comment]
I will need to put some documentation with this first. but then I will submit.
