### ISSUE TITLE
Climate index composite plots

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esmtools#7]
Per @aaronspring in https://github.com/bradyrx/climpred/issues/23#issuecomment-453634686. We should have functions to plot composites of climate indices.

In my EBUS CO2 flux paper, I did some of this, but perhaps not super cleanly. See [#1](https://github.com/bradyrx/EBUS_BGC_Variability/blob/master/scripts/py/full_ensemble_composite_map.py), [#2](https://github.com/bradyrx/EBUS_BGC_Variability/blob/master/scripts/py/composite_nonEOF.py), [#3](https://github.com/bradyrx/EBUS_BGC_Variability/tree/master/notebooks/Composite_Maps) for inspiration.

**Comment by aaronspring** [comment]
https://rabernat.github.io/research_computing/xarray.html
This was my inspiration for raising this.

**Comment by bradyrx** [comment]
Ryan's version looks much cleaner than mine, although I did something similar. This should be pretty easy to implement, but very powerful.

**Comment by bradyrx** [comment]
@aaronspring, for all of these issues, feel free to open a PR whenever you have time or interest (one PR per idea). We can slowly build `esmtools` to incorporate all sorts of things so ideally one day we can do a full research project without developing code :) 

If you want to migrate over any personal functions from your analysis package please feel free to do so as well via a PR. I think we should just aim to have clean code here like in `climpred`. I need to clean up some of my old functions here eventually.

**Comment by bradyrx** [comment]
Addressed in https://github.com/bradyrx/esmtools/pull/16.
