### ISSUE TITLE
corr/autocorr tests breaking at climpred

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esmtools#79]
See https://github.com/bradyrx/climpred/issues/262. This will be migrated over here.

**Comment by aaronspring** [comment]
next xr will have corr and cov. but those wont have the lag keyword so lets keep our implementation

**Comment by bradyrx** [comment]
Effectively closed by https://github.com/bradyrx/esmtools/pull/88. I got rid of `autocorr` since you can just run `corr(x, x)` and renamed `ACF` to `autocorr` to match the pandas language for this. I think the errors were due to different handling of p values, whether that was effective p value or not.
