### ISSUE TITLE
carbon: potential pCO2

### ISSUE THREAD

**Issue by aaronspring** [bradyrx/esmtools#8]
I like the idea of potential pCO2.

From the Sarmiento and Gruber book: Figure 10.3.4: Vertical section of potential pCO2 in the equatorial Pacific. Potential pCO2 is the CO2 pressure a sample would achieve if it were isochemically depressurized (to 1 atm) and warmed (to 25􏰍C) (see text). From Broecker and Peng [1982].

```pCO2_potential = pCO_insitu (1 + 0.0423(T_sfc-T_insitu ))```

In MPI-ESM we dont have pCO2 insitu. Do you in CESM?
I have script that calculates pCO2 based on DIC, Alk, T, S exactly as in our model, but this is long code and definitely wont work fast on maps.

But with S&G Formula (8.3.3) pCO2(Alk,DIC) I think it would work.

**Comment by bradyrx** [comment]
I like this, it sounds similar to potential density, etc. where you can compare something at the deep that is modified by different temp/pressure/salinity to something at the surface.

> In MPI-ESM we dont have pCO2 insitu. Do you in CESM?

If I understand this correctly, yes. We have pCO2 that is output directly from the model, i.e., the calculation you do offline is done at model runtime. 

>  I have script that calculates pCO2 based on DIC, Alk, T, S exactly as in our model, but this is long code and definitely wont work fast on maps.

Have you looked into things like CO2SYS? There's some C-based code that is probably much faster.

For documentation sake on this issue, here are some of the things you referenced from the text:

<img width="394" alt="screen shot 2019-01-13 at 10 07 14 am" src="https://user-images.githubusercontent.com/8881170/51088338-9f8ec300-171b-11e9-8b13-472989b94c1a.png">

<img width="407" alt="screen shot 2019-01-13 at 10 09 28 am" src="https://user-images.githubusercontent.com/8881170/51088333-96055b00-171b-11e9-8667-4c4ef833ce72.png">

<img width="469" alt="screen shot 2019-01-13 at 10 07 43 am" src="https://user-images.githubusercontent.com/8881170/51088337-9c93d280-171b-11e9-8342-ab2c06f92604.png">

**Comment by aaronspring** [comment]
We only have surface pCO2. Not as lon lat depth.

**Comment by bradyrx** [comment]
Addressed in your PR
